### ISSUE TITLE
Bus error with v4l2loopback

### ISSUE THREAD

**Issue by vishwin** [hselasky/webcamd#18]
I seem to get a bus error when launching with `-c v4l2loopback`. Backtrace shows nothing. webcamd itself works otherwise with no flags and spawned with devd.

```
Options        :
        COMPAT32       : off
        DEBUG          : off
        DVB            : on
        INPUT          : on
        KEYBOARD       : on
        MOUSE          : on
        RADIO          : on
        V4L2LOOPBACK   : on
        VT_CLIENT      : off
        VT_SERVER      : off
        WEBCAM         : on
```

**Comment by hselasky** [comment]
Hi,

Can you install gdb from pkg/ports. Then run webcamd inside GDB:

```
gdb111 webcamd
run -c v4l2loopback
bt
```

Which CPU architecture is this?

Works fine with AMD64 over here!

**Comment by hselasky** [comment]
You may also want to re-compile webcamd with DEBUG enabled before running it from GDB.

**Comment by vishwin** [comment]
Yes, this is amd64. Going to see what gdb spits out

**Comment by vishwin** [comment]
```
Reading symbols from webcamd...
(gdb) run -c v4l2loopback
Starting program: /usr/local/sbin/webcamd -c v4l2loopback
warning: Could not load shared library symbols for [vdso].
Do you need "set solib-search-path" or "set sysroot"?
[New LWP 137220 of process 27871]
[New LWP 137221 of process 27871]
[New LWP 137222 of process 27871]
[New LWP 137223 of process 27871]

Thread 1 received signal SIGBUS, Bus error.
Object-specific hardware error.
0x000000000140c225 in find_ref (hdl=0x801e5a078, id=9961473) at media_tree/drivers/media/v4l2-core/v4l2-ctrls.c:2746
2746    media_tree/drivers/media/v4l2-core/v4l2-ctrls.c: No such file or directory.
(gdb) bt
#0  0x000000000140c225 in find_ref (hdl=0x801e5a078, id=9961473) at media_tree/drivers/media/v4l2-core/v4l2-ctrls.c:2746
#1  0x000000000140987b in find_ref_lock (hdl=0x801e5a078, id=9961473) at media_tree/drivers/media/v4l2-core/v4l2-ctrls.c:2762
#2  0x000000000140afb4 in handler_new_ref (hdl=0x801e5a078, ctrl=0x801e78000, ctrl_ref=0x0, from_other_dev=false, allocate_req=false)
    at media_tree/drivers/media/v4l2-core/v4l2-ctrls.c:2798
#3  0x000000000140a569 in v4l2_ctrl_new (hdl=0x801e5a078, ops=0x1632d68 <v4l2loopback_ctrl_ops>, type_ops=0x0, id=10025216, name=0x1099f88 "keep_format",
    type=V4L2_CTRL_TYPE_BOOLEAN, min=0, max=1, step=1, def=0, dims=0x1632270 <v4l2loopback_ctrl_keepformat+80>, elem_size=4, flags=0, qmenu=0x0, qmenu_int=0x0,
    p_def=..., priv=0x0) at media_tree/drivers/media/v4l2-core/v4l2-ctrls.c:3055
#4  0x0000000001409b8b in v4l2_ctrl_new_custom (hdl=0x801e5a078, cfg=0x1632220 <v4l2loopback_ctrl_keepformat>, priv=0x0)
    at media_tree/drivers/media/v4l2-core/v4l2-ctrls.c:3097
#5  0x00000000015e20f1 in v4l2_loopback_add (conf=0x7fffffffe8a8, ret_nr=0x0) at contrib/v4l2loopback/v4l2loopback.c:2504
#6  0x00000000015e18e1 in v4l2loopback_init_module () at contrib/v4l2loopback/v4l2loopback.c:2861
#7  0x00000000011bcee2 in linux_init () at kernel/linux_section.c:50
#8  0x00000000015e9141 in main (argc=3, argv=0x7fffffffea00) at webcamd.c:1017
```

**Comment by hselasky** [comment]
Perfect. What version of webcamd is this?

**Comment by hselasky** [comment]
Hi,

I was not able to reproduce the issue exactly, but valgrind gave some clear hints:

```

==4756== Conditional jump or move depends on uninitialised value(s)
==4756==    at 0x5C762D: find_ref (v4l2-ctrls.c:2746)
==4756==    by 0x5C762D: find_ref_lock (v4l2-ctrls.c:2762)
==4756==    by 0x5C762D: handler_new_ref (v4l2-ctrls.c:2798)
==4756==    by 0x5C6E5B: v4l2_ctrl_new (v4l2-ctrls.c:3055)
==4756==    by 0x5C6934: v4l2_ctrl_new_custom (v4l2-ctrls.c:3097)
==4756==    by 0x7556D5: v4l2_loopback_add (v4l2loopback.c:2504)
==4756==    by 0x7556D5: v4l2loopback_init_module (v4l2loopback.c:2861)
==4756==    by 0x3C5921: linux_init (linux_section.c:50)
==4756==    by 0x75AB02: main (webcamd.c:1017)
```
I found an issue where memory was not zero-initialized like expected, and that is now fixed in v5.13.2.7 :
https://cgit.freebsd.org/ports/commit/?id=209f34d2bf6c29bbd4656281ce927eb5a16c98b1

Let me know if this fixes the issue for you aswell.

**Comment by hselasky** [comment]
Just found an issue in the Linux UVC driver:
https://cgit.freebsd.org/ports/commit/?id=83d156a8f2fceb4bf0b3ff644173b8de034e1e15

**Comment by vishwin** [comment]
This was 5.13.2.6_2 in ports. Going to try the update

**Comment by vishwin** [comment]
Seems to be working now in 5.13.2.8. Got OBS Virtual Camera working in the loopback
